[phases.build]
cmds = [
    "rm -rf dist",
    "mkdir -p dist",
    "cp -f *.html dist/ || true",
    "cp -f *.css dist/ 2>/dev/null || true",
    "cp -f *.js dist/ 2>/dev/null || true",
    "echo 'Files in current directory:' && ls -la *.html",
    "echo 'Files copied to dist:' && ls -la dist/",
    "echo 'Build complete!'"
]

[start]
cmd = "nginx -c /app/nginx.conf -g 'daemon off;'"